### ISSUE TITLE
Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by franshua91** [XunMengWinter/CircularAnim#22]
Hi, my code is the following:

`CircularAnim.fullActivity(MyActivity.this, view).colorOrImageRes(R.color.blue_dark).go(new CircularAnim.OnAnimationEndListener() {
    @Override
    public void onAnimationEnd() {
        startActivity(intent);
    }
});`

The error is:

`Fatal Exception: java.lang.IllegalStateException: Cannot start this animator on a detached view!
       at android.view.RenderNode.addAnimator(RenderNode.java:817)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
       at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
       at android.animation.RevealAnimator.(RevealAnimator.java)
       at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:53)
       at top.wefor.circularanim.CircularAnim$FullActivityBuilder$1$1.run(CircularAnim.java:254)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6102)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)`

It appears on Android 5 and 6.

Thanks.

**Comment by XunMengWinter** [comment]
CircularAnim.fullActivity(MyActivity.this, view)...
 the view must in activity or fragment , cannot in dialog.

**Comment by franshua91** [comment]
But the fullActivity method is inside of onitemclick gridview callback. It only happened on 50 users, it is not the normal behaviour.

Thanks.

**Comment by XunMengWinter** [comment]
I understand, the CircularAnim only effect on api 21 or later, and it not support adapter...
Wait about one hour, I'll add some code to support adapter.
Thanks

**Comment by XunMengWinter** [comment]
oh, but I tested in RecyclerView Adapter, it's working

```
class MyViewHolder extends RecyclerView.ViewHolder {

                public MyViewHolder(View itemView) {
                    super(itemView);
                    Button button = (Button) itemView.findViewById(R.id.button);
                    button.setOnClickListener(new View.OnClickListener() {
                        @Override
                        public void onClick(View view) {
                            CircularAnim.fullActivity(ListActivity.this, view)
                                    .colorOrImageRes(R.color.colorPrimary)
                                    .go(new CircularAnim.OnAnimationEndListener() {
                                        @Override
                                        public void onAnimationEnd() {
                                            startActivity(new Intent(ListActivity.this, MainActivity.class));
                                            finish();
                                        }
                                    });
                        }
                    });
                }
            }
```

**Comment by franshua91** [comment]
Yes, I know that it is working with an adapter because my app is online since 5 days ago with 1 million users and it is all fine except to 50 users up today. I dont know why this error happens because I use the library only to open an activity.

**Comment by XunMengWinter** [comment]
I don't know why it happened, and I can't reappear it, but I try catch it in Version 0.3.2, so, try update~~

**Comment by franshua91** [comment]
Thank you very much.
