### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by nevermoresss** [XunMengWinter/CircularAnim#9]
```
java.lang.IllegalStateException: Cannot start this animator on a detached view!

at android.view.RenderNode.addAnimator(RenderNode.java:812)

at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)

at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)

at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)

at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:55)

at com.xxx.xxx.util.CircularAnimUtil$2$1.run(CircularAnimUtil.java:147)
```

**Comment by XunMengWinter** [comment]
activity里调用动画的代码看一下

**Comment by nevermoresss** [comment]
@XunMengWinter  你好，我的使用场景是这样的，在SignInActivity 登录Button调用这个动画,

```
// 默认显示返回至当前Activity的动画.
   triggerView.postDelayed(new Runnable() {
   @Override
   public void run() {
   Animator anim =   ViewAnimationUtils.createCircularReveal(view, cx, cy, finalRadius, 0);
   .......                       
```

这段代码中，`thisActivity`如果`Destroyed`了，那么`view`就会`detached`,建议做下判断

我的启动代码:

```
Intent intent = new Intent(this, HomeActivity.class);
intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);
CircularAnimUtil.startActivity(this,intent,signInBtn,R.color.color_03A9F4);

```

**Comment by XunMengWinter** [comment]
你更新一下代码，我添加了一个方法startActivityThenFinish()，调用该方法就可以了。
finish动作得在动画结束后执行才行，所以之前那样放后面finish是不行的。

**Comment by amanzan** [comment]
I cannot import CircularAnimUtil with version 0.4.1? It doesn't seem to be included in the release

**Comment by XunMengWinter** [comment]
@amanzan CircularAnim.

**Comment by amanzan** [comment]
But there is no "startActivityThenFinish" method inside CircularAnim...

**Comment by XunMengWinter** [comment]
@amanzan api was changed
use this
```
CircularAnim.fullActivity(MainActivity.this, view)
                        .colorOrImageRes(R.mipmap.img_huoer_black)
                        .go(new CircularAnim.OnAnimationEndListener() {
                            @Override
                            public void onAnimationEnd() {
                                startActivity(new Intent(MainActivity.this, ListActivity.class));
                                // finish(); // if you want to finish this activity.
                            }
                        });
```

**Comment by amanzan** [comment]
great, thanks!
